homework9: main.o pokemon.o charmeleon.o caterpie.o wartortle.o
	g++ -o homework9 main.o pokemon.o charmeleon.o caterpie.o wartortle.o

pokemon.o: pokemon.cpp
	g++ -ansi -pedantic -errors -Wall -c pokemon.cpp

charmeleon.o: charmeleon.cpp
	g++ -ansi -pedantic -errors -Wall -c charmeleon.cpp

caterpie.o: caterpie.cpp
	g++ -ansi -pedantic -errors -Wall -c caterpie.cpp

wartortle.o: wartortle.cpp
	g++ -ansi -pedantic -errors -Wall -c wartortle.cpp

main.o: main.cpp
	g++ -ansi -pedantic -errors -Wall -c main.cpp
